### ISSUE TITLE
how to get dataset

### ISSUE THREAD

**Issue by chasingegg** [wangsibovictor/fora#1]
Seems that I can not get the dataset with your data format like DBLP, I wonder if you can give a link, or could you please provide the scripts to preprocess the dataset.

**Comment by wangsibovictor** [comment]
You may download the datasets from http://konect.uni-koblenz.de/ and https://snap.stanford.edu/data/

**Comment by JRN1** [comment]
I have already configured the environment. Can you recommend me a program editing tool? Thanks very much

**Comment by wangsibovictor** [comment]
It highly depends. Please use the tool that comforts you most (you may google and can find a long list of suggestions).  For me, Vim and Sublime are my favorite editors.
